import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { City } from '../schemas/city.schema';

@Injectable()
export class CitySeed implements OnModuleInit {
  constructor(@InjectModel('City') private readonly cityModel: Model<City>) {}

  async onModuleInit() {
    Logger.log("\x1b[33m[ElandLocationModule]\x1b[32m 🚀 Running Database Seeder for Location service...");

    // Check if roles exist
    const existingCities = await this.cityModel.countDocuments();
    if (existingCities > 0) {
      Logger.log("\x1b[33m[ElandLocationModule]\x1b[32m ✅ cities are aready seeded!");
      return;
    }

    const cities = [
      { name: {fr: "Toronto", en: "Toronto"} },
      { name: {fr: "Montréal", en: "Montreal"} },
      { name: {fr: "Vancouver", en: "Vancouver"} },
      { name: {fr: "Calgary", en: "Calgary"} },
      { name: {fr: "Edmonton", en: "Edmonton"} },
      { name: {fr: "Winnipeg", en: "Winnipeg"} },
      { name: {fr: "Québec", en: "Quebec City"} },
      { name: {fr: "Ottawa", en: "Ottawa"} },
      { name: {fr: "Hamilton", en: "Hamilton"} },
      { name: {fr: "Kitchener", en: "Kitchener"} },
      { name: {fr: "London", en: "London"} },
      { name: {fr: "Victoria", en: "Victoria"} },
      { name: {fr: "Halifax", en: "Halifax"} },
      { name: {fr: "Oshawa", en: "Oshawa"} },
      { name: {fr: "Windsor", en: "Windsor"} },
      { name: {fr: "Saskatoon", en: "Saskatoon"} },
      { name: {fr: "Regina", en: "Regina"} },
      { name: {fr: "St. John's", en: "St. John's"} },
      { name: {fr: "Sudbury", en: "Greater Sudbury"} },
      { name: {fr: "Sherbrooke", en: "Sherbrooke"} },
      { name: {fr: "Barrie", en: "Barrie"} },
      { name: {fr: "Kelowna", en: "Kelowna"} },
      { name: {fr: "Trois-Rivières", en: "Trois-Rivières"} },
      { name: {fr: "Guelph", en: "Guelph"} },
      { name: {fr: "Abbotsford", en: "Abbotsford"} },
      { name: {fr: "Saint John", en: "Saint John"} },
      { name: {fr: "Thunder Bay", en: "Thunder Bay"} },
      { name: {fr: "Lethbridge", en: "Lethbridge"} },
      { name: {fr: "Peterborough", en: "Peterborough"} },
      { name: {fr: "Red Deer", en: "Red Deer"} },
      { name: {fr: "Kamloops", en: "Kamloops"} },
      { name: {fr: "Chatham-Kent", en: "Chatham-Kent"} },
      { name: {fr: "Saguenay", en: "Saguenay"} },
      { name: {fr: "Drummondville", en: "Drummondville"} },
      { name: {fr: "Saint-Jérôme", en: "Saint-Jérôme"} },
      { name: {fr: "Charlottetown", en: "Charlottetown"} },
      { name: {fr: "Brantford", en: "Brantford"} },
      { name: {fr: "Moncton", en: "Moncton"} },
      { name: {fr: "Thunder Bay", en: "Thunder Bay"} },
      { name: {fr: "Medicine Hat", en: "Medicine Hat"} },
      { name: {fr: "Beloeil", en: "Beloeil"} },
      { name: {fr: "Fredericton", en: "Fredericton"} },
      { name: {fr: "Cape Breton", en: "Cape Breton"} },
      { name: {fr: "Granby", en: "Granby"} },
      { name: {fr: "Saint-Jean-sur-Richelieu", en: "Saint-Jean-sur-Richelieu"} },
      { name: {fr: "Saint-Georges", en: "Saint-Georges"} },
      { name: {fr: "Cornwall", en: "Cornwall"} },
      { name: {fr: "North Bay", en: "North Bay"} },
      { name: {fr: "Belleville", en: "Belleville"} },
      { name: {fr: "Prince George", en: "Prince George"} },
      { name: {fr: "Sarnia", en: "Sarnia"} },
      { name: {fr: "Moose Jaw", en: "Moose Jaw"} },
      { name: {fr: "Levis", en: "Lévis"} },
      { name: {fr: "Boucherville", en: "Boucherville"} },
      { name: {fr: "Shawinigan", en: "Shawinigan"} },
      { name: {fr: "Mascouche", en: "Mascouche"} },
      { name: {fr: "Rimouski", en: "Rimouski"} },
      { name: {fr: "Châteauguay", en: "Châteauguay"} },
      { name: {fr: "Sept-Îles", en: "Sept-Îles"} },
      { name: {fr: "Shannon", en: "Shannon"} },
      { name: {fr: "Terrace", en: "Terrace"} },
      { name: {fr: "Fort McMurray", en: "Fort McMurray"} },
      { name: {fr: "Edmundston", en: "Edmundston"} },
      { name: {fr: "Mirabel", en: "Mirabel"} },
      { name: {fr: "Rouyn-Noranda", en: "Rouyn-Noranda"} },
      { name: {fr: "Joliette", en: "Joliette"} },
      { name: {fr: "Lloydminster", en: "Lloydminster"} },
      { name: {fr: "Orangeville", en: "Orangeville"} },
      { name: {fr: "Campbell River", en: "Campbell River"} },
      { name: {fr: "Timmins", en: "Timmins"} },
      { name: {fr: "Duncan", en: "Duncan"} },
      { name: {fr: "Saint-Hyacinthe", en: "Saint-Hyacinthe"} },
      { name: {fr: "Woodstock", en: "Woodstock"} },
      { name: {fr: "Salmon Arm", en: "Salmon Arm"} },
      { name: {fr: "Chilliwack", en: "Chilliwack"} },
      { name: {fr: "Brockville", en: "Brockville"} },
      { name: {fr: "Cornwall", en: "Cornwall"} },
      { name: {fr: "Leduc", en: "Leduc"} },
      { name: {fr: "Cochrane", en: "Cochrane"} },
      { name: {fr: "Yorkton", en: "Yorkton"} },
      { name: {fr: "Parksville", en: "Parksville"} },
      { name: {fr: "Laval", en: "Laval"} },
      { name: {fr: "Longueuil", en: "Longueuil"} },
      { name: {fr: "Repentigny", en: "Repentigny"} },
      { name: {fr: "Blainville", en: "Blainville"} },
      { name: {fr: "Dollard-des-Ormeaux", en: "Dollard-des-Ormeaux"} },
      { name: {fr: "Beauharnois", en: "Beauharnois"} },
      { name: {fr: "Granby", en: "Granby"} },
      { name: {fr: "Mascouche", en: "Mascouche"} },
      { name: {fr: "Boisbriand", en: "Boisbriand"} },
      { name: {fr: "Boucherville", en: "Boucherville"} },
      { name: {fr: "Mont-Saint-Hilaire", en: "Mont-Saint-Hilaire"} },
      { name: {fr: "Sorel-Tracy", en: "Sorel-Tracy"} },
      { name: {fr: "Thetford Mines", en: "Thetford Mines"} },
      { name: {fr: "Châteauguay", en: "Châteauguay"} },
      { name: {fr: "Magog", en: "Magog"} },
      { name: {fr: "Saint-Eustache", en: "Saint-Eustache"} },
      { name: {fr: "Saint-Lin-Laurentides", en: "Saint-Lin-Laurentides"} },
      { name: {fr: "Saint-Bruno-de-Montarville", en: "Saint-Bruno-de-Montarville"} },
      { name: {fr: "Saint-Basile-le-Grand", en: "Saint-Basile-le-Grand"} },
      { name: {fr: "Chambly", en: "Chambly"} },
      { name: {fr: "L'Assomption", en: "L'Assomption"} },
      { name: {fr: "Rimouski", en: "Rimouski"} },
      { name: {fr: "Trois-Rivières", en: "Trois-Rivières"} },
      { name: {fr: "Drummondville", en: "Drummondville"} },
      { name: {fr: "Saint-Jérôme", en: "Saint-Jérôme"} },
      { name: {fr: "Val-d'Or", en: "Val-d'Or"} },
      { name: {fr: "Sept-Îles", en: "Sept-Îles"} },
      { name: {fr: "Victoriaville", en: "Victoriaville"} },
      { name: {fr: "Shawinigan", en: "Shawinigan"} },
      { name: {fr: "Saint-Georges", en: "Saint-Georges"} },
      { name: {fr: "La Tuque", en: "La Tuque"} },
      { name: {fr: "Dolbeau-Mistassini", en: "Dolbeau-Mistassini"} },
      { name: {fr: "Saguenay", en: "Saguenay"} },
      { name: {fr: "Saint-Jean-sur-Richelieu", en: "Saint-Jean-sur-Richelieu"} },
      { name: {fr: "Alma", en: "Alma"} },
      { name: {fr: "Chibougamau", en: "Chibougamau"} },
      { name: {fr: "Baie-Comeau", en: "Baie-Comeau"} },
      { name: {fr: "Amos", en: "Amos"} },
      { name: {fr: "Mont-Laurier", en: "Mont-Laurier"} },
      { name: {fr: "Gaspé", en: "Gaspé"} },
      { name: {fr: "Chandler", en: "Chandler"} },
      { name: {fr: "Port-Cartier", en: "Port-Cartier"} },
      { name: {fr: "Fermont", en: "Fermont"} },
      { name: {fr: "Matane", en: "Matane"} },
      { name: {fr: "Rivière-du-Loup", en: "Rivière-du-Loup"} },
      { name: {fr: "Montmagny", en: "Montmagny"} },
      { name: {fr: "Saint-Félicien", en: "Saint-Félicien"} },
      { name: {fr: "Mont-Tremblant", en: "Mont-Tremblant"} },
      { name: {fr: "Saint-Raymond", en: "Saint-Raymond"} },
      { name: {fr: "Rawdon", en: "Rawdon"} },
      { name: {fr: "Sainte-Adèle", en: "Sainte-Adèle"} },
      { name: {fr: "Valcourt", en: "Valcourt"} },
      { name: {fr: "Baie-Saint-Paul", en: "Baie-Saint-Paul"} },
      { name: {fr: "Saint-Pascal", en: "Saint-Pascal"} },
      { name: {fr: "Mont-Joli", en: "Mont-Joli"} },
      { name: {fr: "Dolbeau", en: "Dolbeau"} },
      { name: {fr: "Saint-Tite", en: "Saint-Tite"} },
      { name: {fr: "La Sarre", en: "La Sarre"} },
      { name: {fr: "Cap-Chat", en: "Cap-Chat"} },
      { name: {fr: "La Malbaie", en: "La Malbaie"} },
      { name: {fr: "Saint-Augustin", en: "Saint-Augustin"} },
      { name: {fr: "Saint-Sauveur", en: "Saint-Sauveur"} },
      { name: {fr: "Louiseville", en: "Louiseville"} },
      { name: {fr: "Val-des-Monts", en: "Val-des-Monts"} },
      { name: {fr: "Montpellier", en: "Montpellier"} },
      { name: {fr: "Dégelis", en: "Dégelis"} },
      { name: {fr: "Saint-Jovite", en: "Saint-Jovite"} },
      { name: {fr: "Sainte-Agathe-des-Monts", en: "Sainte-Agathe-des-Monts"} },
      { name: {fr: "Saint-Martin", en: "Saint-Martin"} },
      { name: {fr: "Tracadie-Sheila", en: "Tracadie-Sheila"} },
      { name: {fr: "Gander", en: "Gander"} },
      { name: {fr: "Grand Falls-Windsor", en: "Grand Falls-Windsor"} },
      { name: {fr: "Labrador City", en: "Labrador City"} },
      { name: {fr: "Corner Brook", en: "Corner Brook"} },
      { name: {fr: "Channel-Port aux Basques", en: "Channel-Port aux Basques"} },
      { name: {fr: "Deer Lake", en: "Deer Lake"} },
      { name: {fr: "Happy Valley-Goose Bay", en: "Happy Valley-Goose Bay"} },
      { name: {fr: "Marystown", en: "Marystown"} },
      { name: {fr: "Carbonear", en: "Carbonear"} },
      { name: {fr: "Stephenville", en: "Stephenville"} },
      { name: {fr: "Clarenville", en: "Clarenville"} },
      { name: {fr: "Springdale", en: "Springdale"} },
      { name: {fr: "Lewisporte", en: "Lewisporte"} },
      { name: {fr: "Placentia", en: "Placentia"} },
      { name: {fr: "Bishop's Falls", en: "Bishop's Falls"} },
      { name: {fr: "Botwood", en: "Botwood"} },
      { name: {fr: "Fogo Island", en: "Fogo Island"} }                      
    ];
    await this.cityModel.insertMany(cities);
    Logger.log("\x1b[33m[ElandLocationModule]\x1b[32m ✅ cities seeded successfully!");
  }
}