import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Schema as MongooseSchema } from 'mongoose';

@Schema()
export class ProtectedDocument extends Document {
  @Prop({required: true})
  ownerId: MongooseSchema.Types.ObjectId
  
  @Prop({ required: true })
  path: string; 

  // The unique filename generated by Multer/S3
  @Prop({ required: true })
  filename: string;

  // The original name provided by the user
  @Prop({ required: true })
  originalName: string;

  // The MIME type (e.g., 'image/jpeg', 'application/pdf')
  @Prop()
  mimetype: string;
  
  @Prop()
  base64: string;

  // The size of the file in bytes
  @Prop()
  size: number;

  // ID of the parent entity (Property ID, Lease ID, etc.)
  @Prop({ required: true })
  entityId: MongooseSchema.Types.ObjectId; 

  // Whether the file requires authentication to view (e.g., leases)
  @Prop({ default: false })
  isProtected: boolean; 

  @Prop({ default: Date.now })
  uploadDate: Date;
}

export const ProtectedDocumentSchema = SchemaFactory.createForClass(ProtectedDocument);